-- 用户表（以手机号为唯一标识）
CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    mobile VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL,
    nickname VARCHAR(64),
    status VARCHAR(16) NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

